# Generated by Django 5.2.4 on 2025-10-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_merge_20250811_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='blockchain_item_id',
            field=models.IntegerField(blank=True, help_text='The unique ID of this item on the blockchain.', null=True, unique=True),
        ),
    ]
